use_frameworks!

platform :ios, '9.0'

target 'JGPodLibrary_Example' do
  pod 'JGPodLibrary', :path => '../'
  pod 'Alamofire', '~> 4.7'

  target 'JGPodLibrary_Tests' do
    inherit! :search_paths

    
  end
end
